### ISSUE TITLE
Inconsistent Testing

### ISSUE THREAD

**Issue by dhinojosa** [http4s/http4s-tomcat#194]
Testing works, but every once in a while, a `NullPointerException` is thrown by `servlet.WriteListener`

```sh
java.lang.NullPointerException: Cannot invoke "org.apache.catalina.connector.OutputBuffer.setWriteListener(jakarta.servlet.WriteListener)" because "this.ob" is nullte 4s
	at org.apache.catalina.connector.CoyoteOutputStream.setWriteListener(CoyoteOutputStream.java:171)
	at org.http4s.servlet.NonBlockingServletIo.$anonfun$bodyWriter$7(ServletIo.scala:174)
	at delay @ org.http4s.servlet.NonBlockingServletIo.$anonfun$bodyWriter$6(ServletIo.scala:174)
```

**Comment by rossabaker** [comment]
I think this is the first http4s-tomcat since https://github.com/http4s/http4s-servlet/pull/50.  I suspect we're making a bad assumption there...
